[project]
project_id = "cast-flow"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
