name: Auto Post Scheduler

on:
  schedule:
    # Run every 15 minutes (much better than Vercel Hobby's hourly + delays)
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  process-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Secrets
      env:
        VERCEL_URL: ${{ secrets.VERCEL_URL }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
      run: |
        if [ -z "$VERCEL_URL" ]; then
          echo "❌ VERCEL_URL secret is not set"
          exit 1
        fi
        if [ -z "$CRON_SECRET" ]; then
          echo "❌ CRON_SECRET secret is not set"
          exit 1
        fi
        echo "✅ All secrets are configured"
        
    - name: Process Scheduled Posts
      env:
        VERCEL_URL: ${{ secrets.VERCEL_URL }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
      run: |
        echo "🚀 Processing scheduled posts..."
        echo "Calling: $VERCEL_URL/api/manual-process-posts"
        
        response=$(curl -s -w "%{http_code}" -X POST "$VERCEL_URL/api/manual-process-posts" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $CRON_SECRET")
        
        http_code="${response: -3}"
        body="${response%???}"
        
        echo "HTTP Status: $http_code"
        echo "Response Body: $body"
        
        if [ "$http_code" -eq 200 ]; then
          echo "✅ Successfully processed posts"
        else
          echo "❌ Failed to process posts (HTTP $http_code)"
          echo "Response: $body"
          exit 1
        fi
